name: 'GuiMaker'
version: 'v2.0'
main: 'dev.perryplaysmc.plugin.Main'
author: PerryPlaysMC
description: 'Creates a file with inventory data'
api-version: 1.13

commands:
  makegui:
    description: 'Makes chest contents into a gui in a .txt file'
  edititem:
    description: 'Easily edit an item''s Name/Lore'
    aliases: ['ei', 'itemedit', 'ie', 'editi', 'iedit', 'iteme']